- operation: Add
  participant_description:
    name: pinky_54
    group: pinky_fleet
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.059999999999999998
        - 0.20000000000000001
- operation: Add
  participant_description:
    name: pinky_18
    group: pinky_fleet
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: 0
      vicinity:
        type: Circle
        index: 1
      shape_context:
        - 0.059999999999999998
        - 0.20000000000000001